Fixes for ShellCheck errors
thomasfr/hass-addons pull request #6
Opened 2023-03-04 21:56 UTC by atrepca

Running the script through the [shellcheck](https://github.com/koalaman/shellcheck) static analysis tool returns the errors below:
```sh
$ shellcheck run.sh 

In run.sh line 1:
#!/usr/bin/with-contenv bashio
^-- SC1008 (error): This shebang was unrecognized. ShellCheck only supports sh/bash/dash/ksh. Add a 'shell' directive to specify.

In run.sh line 17:
export AWS_ACCESS_KEY_ID="$(bashio::config 'aws_access_key')"
       ^---------------^ SC2155 (warning): Declare and assign separately to avoid masking return values.

In run.sh line 18:
export AWS_SECRET_ACCESS_KEY="$(bashio::config 'aws_secret_access_key')"
       ^-------------------^ SC2155 (warning): Declare and assign separately to avoid masking return values.

For more information:
  https://www.shellcheck.net/wiki/SC1008 -- This shebang was unrecognized. Sh...
  https://www.shellcheck.net/wiki/SC2155 -- Declare and assign separately to ...
```

SC2155 is detailed [here](https://www.shellcheck.net/wiki/SC2155), and SC1008 [here](https://www.shellcheck.net/wiki/SC1008).

ShellCheck can also run as a [GitHub action](https://github.com/marketplace/actions/shellcheck).

Also removed the executable bit from other non-executables that had it.

2023-03-30 12:52 UTC, thomasfr requested changes
Thank you very much. Did not know shellcheck tbh and was not aware of SC2155. So thanks for that. 
If you or someone else interested in contributing, i would also accept a PR for enabling ShellCheck within Github Actions.

2023-03-30 12:52 UTC, thomasfr commented on amazon-s3-backup/run.sh
> +AWS_ACCESS_KEY_ID="$(bashio::config 'aws_access_key')"; export AWS_ACCESS_KEY_ID
```suggestion
AWS_ACCESS_KEY_ID="$(bashio::config 'aws_access_key')"
export AWS_ACCESS_KEY_ID
```

2023-03-30 12:52 UTC, thomasfr commented on amazon-s3-backup/run.sh
> +AWS_SECRET_ACCESS_KEY="$(bashio::config 'aws_secret_access_key')"; export AWS_SECRET_ACCESS_KEY
```suggestion
AWS_SECRET_ACCESS_KEY="$(bashio::config 'aws_secret_access_key')"
export AWS_SECRET_ACCESS_KEY
```

2024-10-24 15:49 UTC, atrepca commented
Hi @thomasfr, I updated this to add new lines as requested, thanks.

2024-10-24 16:47 UTC, atrepca commented
Also opened #20 to add a ShellCheck GitHub action.

2024-10-24 16:53 UTC, closed without merging